name: Deploy to k8s

on:
  push:
    branches:
      - master

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Docker Image
      uses: docker/setup-buildx-action@v2
      with:
        context: .
        push: true

    - name: Deploy to k8s
      uses: tale/kubectl-action@v1
      with:
        args: apply -f /examples/deployment.yml

